# URL of the API reference table of contents
# check out if you have the latest version url here:
# http://cloudstack.apache.org/docs/api/index.html
#api_ref_toc_url: http://cloudstack.apache.org/docs/api/apidocs-4.2/TOC_Root_Admin.html 
api_ref_toc_url: http://cloudstack.apache.org/docs/api/apidocs-4.4/TOC_Domain_Admin.html
#api_ref_toc_url: http://cloudstack.apache.org/docs/api/apidocs-4.2/TOC_User.html 

# API level (domain_admin, root_admin or user)
#apilevel: root_admin
apilevel: domain_admin
#apilevel: user

# Language for generated code (supported: php, python)
language: php

# Generated class name
class_name: CloudStackClient

# Use camel case variable or not
use_camel_case: true

# Camel case values
camel_case:
  accept: accept
  account: account
  accountdetails: accountDetails
  accountid: accountId
  accounts: accounts
  accounttype: accountType
  aclid: aclId
  action: action
  acltype: aclType
  activeonly: activeOnly
  affinitygroupid: affinityGroupId
  affinitygroupids: affinityGroupIds
  affinitygroupnames: affinityGroupNames
  aggregatename: aggregateName
  algorithm: algorithm
  allocatedonly: allocatedOnly
  allocationstate: allocationState
  applied: applied
  associatednetworkid: associatedNetworkId
  autoscaleuserid: autoscaleUserId
  availability: availability
  available: available
  binddn: bindDN
  bindpass: bindPass
  bits: bits
  bootable: bootable
  broadcastdomainrange: broadcastDomainRange
  canusefordeploy: canUseForDeploy
  category: category
  certchain: certChain
  certid: certId
  certificate: certificate
  changecidr: changeCidr
  checksum: checksum
  cidr: cidr
  cidrlist: cidrList
  cleanup: cleanup
  clusterid: clusterId
  clustername: clusterName
  clustertype: clusterType
  conditionid: conditionId
  conditionids: conditionIds
  conservemode: conserveMode
  counterid: counterId
  counterparam: counterParam
  cpunumber: cpuNumber
  cpuspeed: cpuSpeed
  customer: customer
  customid: customId
  customized: customized
  description: description
  destinationphysicalnetworkid: destinationPhysicalNetworkId
  destroyvmgraceperiod: destroyVmGracePeriod
  destzoneid: destZoneId
  deploymentplanner: deploymentPlanner
  details: details
  deviceid: deviceId
  dhcpprovider: dhcpProvider
  diskofferingid: diskOfferingId
  disksize: diskSize
  displayname: displayName
  displaynetwork: displayNetwork
  displaytext: displayText
  displayvm: displayVm
  displayvolume: displayVolume
  dns1: dns1
  dns2: dns2
  dnssearchorder: dnsSearchOrder
  domain: domain
  domainId: domainId
  domainid: domainId
  domainsuffix: domainSuffix
  dpd: dpd
  duration: duration
  email: email
  enabled: enabled
  enddate: endDate
  endip: endIp
  endipv6: endIpV6
  endport: endPort
  entrytime: entryTime
  esplifetime: espLifeTime
  esppolicy: espPolicy
  expunge: expunge
  fetchlatest: fetchLatest
  fingerprint: fingerprint
  firstname: firstName
  fordisplay: forDisplay
  forced: forced
  forcedestroylocalstorage: forceDestroyLocalStorage
  forloadbalancing: forLoadBalancing
  format: format
  forvirtualnetwork: forVirtualNetwork
  forvpc: forVpc
  fwdevicecapacity: fwDeviceCapacity
  fwdeviceid: fwDeviceId
  gateway: gateway
  gatewayid: gatewayId
  gslbdomainname: gslbDomainName
  gslblbmethod: gslblbMethod
  gslbservicetype: gslbServiceType
  gslbstickysessionmethodname: gslbStickySessionMethodName
  gslblbruleweightsmap: gslblbRuleWeightsMap
  group: group
  groupid: groupId
  guestcidraddress: guestCidrAddress
  guestiptype: guestIpType
  guestvmcidr: guestVmCidr
  haenable: haEnable
  healthythreshold: healthyTreshold
  hostid: hostId
  hostname: hostname
  hosttags: hosttags
  hypervisor: hypervisor
  icmpcode: icmpCode
  icmptype: icmpType
  id: id
  ids: ids
  ikelifetime: ikeLifeTime
  ikepolicy: ikePolicy
  imagestoreuuid: imageStoreUuid
  inline: inline
  instanceport: instancePort
  internaldns1: internalDns1
  internaldns2: internalDns2
  interval: interval
  intervaltime: intervalTime
  intervaltype: intervalType
  ip6address: ip6Address
  ip6cidr: ip6Cidr
  ip6gateway: ip6Gateway
  ipaddress: ipAddress
  ipaddressid: ipAddressId
  iprange: ipRange
  ipsecpsk: ipsecPsk
  iptonetworklist: ipToNetWorkList
  iqn: iqn
  iscleanuprequired: isCleanUpRequired
  isdefault: isDefault
  isdynamicallyscalable: isDynamicallyScalable
  isextractable: isExtractable
  isfeatured: isFeatured
  isoid: isoId
  isofilter: isoFilter
  isolatedpvlan: isolatedPvlan
  isolationmethods: isolationMethods
  isportable: isPortable
  ispublic: isPublic
  isready: isReady
  isrecursive: isRecursive
  isrouting: isRouting
  isshared: isShared
  issourcenat: isSourceNat
  isstaticnat: isStaticNat
  issystem: isSystem
  istagged: isTagged
  jobid: jobId
  quiescevm: quiesceVm
  key: key
  keyboard: keyboard
  keypair: keyPair
  keyword: keyword
  kvmnetworklabel: kvmNetworkLabel
  lastname: lastname
  lbdevicecapacity: lbDeviceCapacity
  lbdevicededicated: lbDeviceDedicated
  lbdeviceid: lbDeviceId
  lbruleid: lbruleId
  lbvmips: lbVmIps
  level: level
  limitcpuuse: limitCpuUse
  listall: listAll
  livemigrate: liveMigrate
  loadbalancerrulelist: loadBalancerRuleList
  lock: lock
  managedstate: managedState
  max: max
  maxguestslimit: maxGuestsLimit
  maxiops: maxIops
  maxmembers: maxMembers
  maxsnaps: maxSnaps
  memory: memory
  methodname: methodName
  miniops: minIops
  minmembers: minMembers
  mode: mode
  name: name
  netmask: netmask
  networkdeviceparameterlist: networkDeviceParameterList
  networkdevicetype: networkDeviceType
  networkdomain: networkDomain
  networkid: networkId
  networkids: networkIds
  networkofferingid: networkOfferingId
  networkrate: networkRate
  networkspeed: networkSpeed
  networktype: networkType
  newname: newName
  nicid: nicId
  nspid: nspId
  number: number
  offerha: offerHa
  op: op
  openfirewall: openFirewall
  oscategoryid: osCategoryId
  ostypeid: osTypeId
  otherdeployparams: otherDeployParams
  page: page
  pagesize: pageSize
  param: param
  parentdomainid: parentDomainId
  passive: passive
  password: password
  passwordenabled: passwordEnabled
  path: path
  pingpath: pingPath
  physicalnetworkid: physicalNetworkId
  podid: podId
  policyid: policyId
  poolname: poolName
  port: port
  privateendport: privateEndPort
  privateip: privateIp
  privatekey: privateKey
  privateport: privatePort
  projectid: projectId
  projectids: projectids
  protocol: protocol
  provider: provider
  providertype: providerType
  publicendport: publicEndPort
  publicipid: publicIpId
  publickey: publicKey
  publicport: publicPort
  queryfilter: queryFilter
  quiettime: quietTime
  regionid: regionId
  relationaloperator: relationalOperator
  requireshvm: requireShvm
  resourceid: resourceid
  resourceids: resourceIds
  resourcestate: resourcestate
  resourcetype: resourceType
  responsetimeout: responseTimeout
  restartrequired: restartRequired
  role: role
  rootdisksize: rootDiskSize
  s2scustomergatewayid: s2sCustomerGatewayId
  s2svpngatewayid: s2sVpnGatewayId
  scaledownpolicyids: scaleDownPolicyIds
  scaleuppolicyids: scaleUpPolicyIds
  schedule: schedule
  scheme: scheme
  showremoved: showRemoved
  shrinkok: shrinkOk
  searchbase: searchBase
  securitygroupenabled: securityGroupEnabled
  securitygroupid: securityGroupId
  securitygroupids: securityGroupIds
  securitygroupname: securityGroupName
  securitygroupnames: securityGroupNames
  service: service
  servicecapabilitylist: serviceCapabilityList
  servicelist: serviceList
  serviceofferingid: serviceOfferingId
  serviceproviderlist: serviceProviderList
  sourceipaddressnetworkid: sourceIpAddressNetworkId
  showcapacities: showCapacities
  size: size
  snapshotid: snapshotId
  snapshotmemory: snapshotMemory
  snapshotpolicy: snapshotPolicy
  snapshotreservation: snapshotReservation
  snapshottype: snapshotType
  sortby: sortBy
  sortkey: sortKey
  source: source
  sourceipaddress: sourceIpAddress
  sourcenatsupported: sourceNatSupported
  sourceport: sourcePort
  sourcezoneid: sourceZoneId
  specifyipranges: specifyIpRanges
  specifyvlan: specifyVlan
  sshkeyenabled: sshkeyEnabled
  ssl: ssl
  start: start
  startdate: startDate
  startip: startIp
  startipv6: startIpV6
  startport: startPort
  startvm: startVm
  state: state
  storageid: storageId
  storagetype: storageType
  subdomainaccess: subDomainAccess
  supportedservices: supportedServices
  systemvmtype: systemVmType
  tags: tags
  templatefilter: templateFilter
  templateid: templateId
  templatetag: templateTag
  threshold: threshold
  timezone: timezone
  token: token
  traffictype: trafficType
  truststore: trustStore
  truststorepass: trustStorePass
  type: type
  unhealthythreshold: unhealthyThreshold
  url: url
  userapikey: userApiKey
  userdata: userData
  userid: userId
  username: userName
  usersecretkey: userSecretKey
  usersecuritygrouplist: userSecurityGroupList
  value: value
  version: version
  virtualmachineid: virtualMachineId
  virtualmachineids: virtualMachineIds
  vlan: vlan
  vlanid: vlanId
  vmidipmap: vmIdIpMap
  vmgroupid: vmGroupId
  vmguestip: vmGuestIp
  vmprofileid: vmProfileId
  vmsnapshotid: vmSnapshotId
  vmwarenetworklabel: vmwareNetworkLabel
  volumeid: volumeId
  volumename: volumeName
  vpcid: vpcId
  vpcofferingid: vpcOfferingId
  xennetworklabel: xenNetworkLabel
  zoneid: zoneId
